# Generated by Django 5.2.4 on 2025-07-06 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founditem',
            name='guardID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.securityguard'),
        ),
    ]
