# Generated by Django 5.2.4 on 2025-07-08 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_founditem_guardid'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProfileAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FoundItemAdmin',
            fields=[
                ('itemID', models.AutoField(primary_key=True, serialize=False)),
                ('itemName', models.CharField(max_length=100)),
                ('itemDescription', models.TextField()),
                ('itemImage', models.ImageField(upload_to='found_items/')),
                ('foundLocation', models.CharField(max_length=255)),
                ('foundDate', models.DateField()),
                ('foundBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='found_items', to='myapp.securityguard')),
                ('guard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.securityguard')),
            ],
        ),
        migrations.CreateModel(
            name='LostItemAdmin',
            fields=[
                ('itemID', models.AutoField(primary_key=True, serialize=False)),
                ('itemName', models.CharField(max_length=100)),
                ('itemDescription', models.TextField()),
                ('itemImage', models.ImageField(upload_to='lost_items/')),
                ('lostDate', models.DateField()),
                ('lostLocation', models.CharField(max_length=255)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='SecurityGuardAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guardID', models.IntegerField(unique=True)),
                ('guardName', models.CharField(max_length=100)),
                ('guardEmail', models.EmailField(max_length=254, unique=True)),
                ('guardImage', models.ImageField(upload_to='guards/')),
                ('guardAddress', models.CharField(max_length=255)),
                ('guardPhone', models.CharField(max_length=15)),
                ('guardDOB', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentID', models.IntegerField(unique=True)),
                ('course', models.CharField(max_length=100)),
                ('studentName', models.CharField(max_length=100)),
                ('studentEmail', models.EmailField(max_length=254, unique=True)),
                ('studentImage', models.ImageField(upload_to='students/')),
                ('studentAddress', models.CharField(max_length=255)),
                ('studentPhone', models.CharField(max_length=15)),
                ('studentDOB', models.DateField()),
                ('studentGender', models.CharField(max_length=10)),
                ('studentYear', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
