from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('register/', views.register, name='register'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('dashboard/index.php', views.dashboard, name='dashboard_index_php'),
    path('dashboard/search', views.search, name='dashboard_search_html'),
    path('record/', views.record, name='record'),
    path('report/', views.report, name='report'),
    path('search/', views.search, name='search'),
    path('security-guard/', views.security_guard, name='security_guard'),
    path('security-guard-login/', views.security_guard_login, name='security_guard_login'),
    path('sgdashboard/', views.sg_dashboard, name='sgdashboard'),
    path('student/', views.student, name='student'),
    path('upload/', views.upload, name='upload'),
    path('verify/', views.verify, name='verify'),
    path('view/', views.view_page, name='view'),
    path('api/found-items/', views.found_items_api, name='api_found_items'),
    path('dashboard/report.html', views.report, name='dashboard_report_html'),
    path('view/record.html', views.record, name='view_record_html'),
    path('view/record', views.record, name='view_record'),
    path('Security Guard.html', views.security_guard, name='security_guard_html'),
    path('student.html', views.student, name='student_html'),
    path('api/securityguards/', views.api_securityguards, name='api_securityguards'),
    path('register.html', views.register, name='register_html'),
    path('index.html', views.home, name='index_html'),
    path('dashboard.html', views.dashboard, name='dashboard_html'),
    path('record.html', views.record, name='record_html'),
    path('report.html', views.report, name='report_html'),
    path('search.html', views.search, name='search_html'),
    path('sgdashboard.html', views.sg_dashboard, name='sgdashboard_html'),
    path('student.html', views.student, name='student_html'),
    path('upload.html', views.upload, name='upload_html'),
    path('verify.html', views.verify, name='verify_html'),
    path('view.html', views.view_page, name='view_html'),
    path('Securityguardlogin.html', views.security_guard_login, name='securityguardlogin_html'),
    path('nav.html', views.home, name='nav_html'),
    path('index.php', views.home, name='index_php'),
    path('nav.php', views.home, name='nav_php'),
    path('view/sgdashboard.html', views.sg_dashboard, name='view_sgdashboard_html'),
    path('record/view.html', views.view_page, name='record_view_html'),
    path('record/sgdashboard.html', views.sg_dashboard, name='record_sgdashboard_html'),
    path('record/view/record.html', views.sg_dashboard, name='record_view_record_html'),
    path('record/record.html', views.record, name='record_record_html'),
    path('record/view/sgdashboard.html', views.sg_dashboard, name='record_view_sgdashboard_html'),
    path('dashboard/report.html', views.report, name='dashboard_report_html'),
    path('dashboard/search.html', views.search, name='dashboard_search_html'),
    path('dashboard/index.php', views.dashboard, name='dashboard_index_php'),
    path('dashboard/index.html', views.dashboard, name='dashboard_index_html'),
    path('dashboard/report.html', views.report, name='dashboard_report_html'),
    path('dashboard/search.html', views.search, name='dashboard_search_html'),
    path('dashboard/register.html', views.register, name='dashboard_register_html'),
    path('report/index.html', views.report, name='report_index_html'),
    path('report/record.html', views.record, name='report_record_html'),
    path('report/search.html', views.search, name='report_search_html'),
    path('report/sgdashboard.html', views.sg_dashboard, name='report_sgdashboard_html'),
    path('report/view.html', views.view_page, name='report_view_html'),
    path('report/upload.html', views.upload, name='report_upload_html'),
    path('dashboard/sgdashboard.html', views.sg_dashboard, name='dashboard_sgdashboard_html'),
    path('dashboard/upload.html', views.upload, name='dashboard_upload_html'),
    path('dashboard/dashboard.html', views.dashboard, name='dashboard_dashboard_html'),
    path('dashboard/nav.html', views.home, name='dashboard_nav_html'),
    path('dashboard/nav.php', views.home, name='dashboard_nav_php'),
    path('dashboard/view.html', views.view_page, name='dashboard_view_html'),
    path('dashboard/student.html', views.student, name='dashboard_student_html'),
    path('dashboard/Securityguardlogin.html', views.security_guard_login, name='dashboard_securityguardlogin_html'),
    path('dashboard/Security Guard.html', views.security_guard, name='dashboard_security_guard_html'),
    path('dashboard/record.html', views.record, name='dashboard_record_html'),
    path('dashboard/search.php', views.search, name='dashboard_search_php'),
    path('dashboard/report.php', views.report, name='dashboard_report_php'),
    path('dashboard/register.php', views.register, name='dashboard_register_php'),
    path('dashboard/upload.php', views.upload, name='dashboard_upload_php'),
    path('dashboard/verify.html', views.verify, name='dashboard_verify_html'),
    path('dashboard/verify.php', views.verify, name='dashboard_verify_php'),
    path('dashboard/view.php', views.view_page, name='dashboard_view_php'),
    path('dashboard/sgdashboard.php', views.sg_dashboard, name='dashboard_sgdashboard_php'),
    path('dashboard/student.php', views.student, name='dashboard_student_php'),
    path('dashboard/Security Guard.php', views.security_guard, name='dashboard_security_guard_php'),
    path('dashboard/Securityguardlogin.php', views.security_guard_login, name='dashboard_securityguardlogin_php'),
    path('dashboard/record.php', views.record, name='dashboard_record_php'),

]




